type User {
  id: ID!
  name: String
  email: String
  isRegistered: Boolean
  numberOfFollowers: Int
  follower(id: ID!): User
  followers(limit: Int): [User]!
}

input RegisterUserInput {
  name: String!
  email: String!
}

type Query {
  user(id: ID!): User
  followers(id: ID!, limit: Int): [User]!
}

type Mutation {
  registerUser(input: RegisterUserInput!): User!
}

type Subscription {
  onUserChange(id: ID!): User!
}
