enum UserStatus {
  ACTIVE
  INACTIVE
}

type Tweet {
  id: ID!
  content: String!
  author: User!
}

type User {
  id: ID!
  name: String
  email: String
  isRegistered: Boolean
  numberOfFollowers: Int
  status: UserStatus
  follower(id: ID!): User
  followers(limit: Int): [User]!
}

input RegisterUserInput {
  name: String!
  email: String!
}

type Query {
  me: User
  user(id: ID!): User
  tweet(id: ID!): Tweet
  followers(id: ID!, limit: Int): [User]!
}

type Mutation {
  registerUser(input: RegisterUserInput!): User!
  setUserStatus(id: ID!, status: UserStatus!): User!
  signIn: User!
}

type Subscription {
  onUserChange(id: ID!): User!
}
